name: test1
channels:
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2021.10.8=h5b45459_0
  - icu=64.2=he025d50_1
  - intel-openmp=2022.0.0=h57928b3_3663
  - jbig=2.1=h8d14728_2003
  - jpeg=9e=h8ffe710_0
  - lerc=3.0=h0e60522_0
  - libblas=3.9.0=13_win64_mkl
  - libcblas=3.9.0=13_win64_mkl
  - libdeflate=1.10=h8ffe710_0
  - liblapack=3.9.0=13_win64_mkl
  - liblapacke=3.9.0=13_win64_mkl
  - libpng=1.6.37=h1d00b33_2
  - libtiff=4.3.0=hc4061b1_3
  - libwebp=1.0.2=hfa6e2cd_5
  - libzlib=1.2.11=h8ffe710_1013
  - lz4-c=1.9.3=h8ffe710_1
  - mkl=2022.0.0=h0e2418a_796
  - numpy=1.21.5=py37h5fa1a60_0
  - opencv=4.1.0=py37hb4945ee_6
  - openssl=1.1.1n=h8ffe710_0
  - pip=22.0.4=pyhd8ed1ab_0
  - python=3.7.12=h7840368_100_cpython
  - python_abi=3.7=2_cp37m
  - qt=5.9.7=h506e8af_3
  - setuptools=60.10.0=py37h03978a9_0
  - sqlite=3.37.1=h8ffe710_0
  - tbb=2021.5.0=h2d74725_0
  - ucrt=10.0.20348.0=h57928b3_0
  - vc=14.2=hb210afc_6
  - vs2015_runtime=14.29.30037=h902a5da_6
  - wheel=0.37.1=pyhd8ed1ab_0
  - xz=5.2.5=h62dcd97_1
  - zlib=1.2.11=h8ffe710_1013
  - zstd=1.5.2=h6255e5f_0
  - pip:
    - albumentations==1.1.0
    - backcall==0.2.0
    - certifi==2021.10.8
    - charset-normalizer==2.0.12
    - click==8.0.4
    - cog==0.0.3
    - colorama==0.4.4
    - coral-pytorch==1.2.0
    - coremltools==5.2.0
    - cycler==0.11.0
    - cython==0.29.28
    - decorator==5.1.1
    - flask==2.0.3
    - fonttools==4.31.2
    - idna==3.3
    - imageio==2.16.1
    - importlib-metadata==4.11.3
    - ipython==7.32.0
    - itsdangerous==2.1.2
    - jedi==0.18.1
    - jinja2==3.1.0
    - joblib==1.1.0
    - kiwisolver==1.4.0
    # - lap==0.4.0
    - markupsafe==2.1.1
    - matplotlib==3.5.1
    - matplotlib-inline==0.1.3
    - mpmath==1.2.1
    - networkx==2.6.3
    - packaging==21.3
    - pafy==0.5.5
    - pandas==1.3.5
    - parso==0.8.3
    - pickleshare==0.7.5
    - pillow==9.0.1
    - prompt-toolkit==3.0.28
    - protobuf==3.19.4
    - psutil==5.9.0
    - pygments==2.11.2
    - pyparsing==3.0.7
    - python-dateutil==2.8.2
    - pytz==2022.1
    - pywavelets==1.3.0
    - pyyaml==6.0
    - qudida==0.0.4
    - requests==2.27.1
    - scikit-image==0.19.2
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - seaborn==0.11.2
    - six==1.16.0
    - sympy==1.10.1
    - thop==0.0.31-2005241907
    - threadpoolctl==3.1.0
    - tifffile==2021.11.2
    - timm==0.5.4
    - torch==1.11.0
    - torchvision==0.12.0
    - tqdm==4.63.1
    - traitlets==5.1.1
    - typing-extensions==4.1.1
    - urllib3==1.26.9
    - wcwidth==0.2.5
    - werkzeug==2.0.3
    - zipp==3.7.0
prefix: C:\Users\Dell\anaconda3\envs\test1
