name: ByteTrack
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - argon2-cffi=20.1.0=py36h27cfd23_1
  - async_generator=1.10=py36h28b3542_0
  - attrs=21.4.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - bleach=4.1.0=pyhd3eb1b0_0
  - ca-certificates=2022.2.1=h06a4308_0
  - certifi=2021.5.30=py36h06a4308_0
  - cffi=1.14.6=py36h400218f_0
  - dbus=1.13.18=hb2f20db_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.3=py36_0
  - expat=2.4.4=h295c915_0
  - fontconfig=2.13.1=h6c09931_0
  - freetype=2.11.0=h70c0345_0
  - glib=2.69.1=h4ff587b_1
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - icu=58.2=he6710b0_3
  - ipykernel=5.3.4=py36h5ca1d4c_0
  - ipython=7.16.1=py36h5ca1d4c_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  - jedi=0.17.0=py36_0
  - jinja2=3.0.3=pyhd3eb1b0_0
  - jpeg=9d=h7f8727e_0
  - jsonschema=3.0.2=py36_0
  - jupyter=1.0.0=py36_7
  - jupyter_client=7.1.2=pyhd3eb1b0_0
  - jupyter_console=6.4.3=pyhd3eb1b0_0
  - jupyter_core=4.8.1=py36h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libuuid=1.0.3=h7f8727e_2
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.12=h03d6c58_0
  - markupsafe=2.0.1=py36h27cfd23_0
  - mistune=0.8.4=py36h7b6447c_0
  - nbclient=0.5.3=pyhd3eb1b0_0
  - nbconvert=6.0.7=py36_0
  - nbformat=5.1.3=pyhd3eb1b0_0
  - ncurses=6.3=h7f8727e_2
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - notebook=6.4.3=py36h06a4308_0
  - openssl=1.1.1m=h7f8727e_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandoc=2.12=h06a4308_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre=8.45=h295c915_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=21.2.2=py36h06a4308_0
  - prometheus_client=0.13.1=pyhd3eb1b0_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - prompt_toolkit=3.0.20=hd3eb1b0_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyqt=5.9.2=py36h05f1152_2
  - pyrsistent=0.17.3=py36h7b6447c_0
  - python=3.6.13=h12debd9_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pyzmq=22.2.1=py36h295c915_1
  - qt=5.9.7=h5867ecd_1
  - qtconsole=5.2.2=pyhd3eb1b0_0
  - qtpy=1.11.2=pyhd3eb1b0_0
  - readline=8.1.2=h7f8727e_1
  - send2trash=1.8.0=pyhd3eb1b0_1
  - sip=4.19.8=py36hf484d3e_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.38.0=hc218d9a_0
  - terminado=0.9.4=py36h06a4308_0
  - testpath=0.5.0=pyhd3eb1b0_0
  - tk=8.6.11=h1ccaba5_0
  - tornado=6.1=py36h27cfd23_0
  - traitlets=4.3.3=py36h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py36_1
  - wheel=0.37.1=pyhd3eb1b0_0
  - widgetsnbextension=3.5.1=py36_0
  - xz=5.2.5=h7b6447c_0
  - zeromq=4.3.4=h2531618_0
  - zlib=1.2.11=h7f8727e_4
  - pip:
    - aiocontextvars==0.2.2
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - albumentations==1.0.3
    - antlr4-python3-runtime==4.8
    - async-timeout==4.0.2
    - asynctest==0.13.0
    - beautifulsoup4==4.10.0
    - blis==0.7.6
    - cachetools==4.2.4
    - catalogue==2.0.6
    - charset-normalizer==2.0.12
    - click==8.0.4
    - contextvars==2.4
    - coral-pytorch==1.2.0
    - cycler==0.11.0
    - cymem==2.0.6
    - dataclasses==0.6
    - decorator==4.4.2
    - docker-pycreds==0.4.0
    - easydict==1.9
    - effdet==0.2.4
    - fastai==2.5.3
    - fastcore==1.3.29
    - fastdownload==0.0.5
    - fastprogress==1.0.2
    - filelock==3.4.1
    - filterpy==1.4.5
    - fire==0.4.0
    - flake8==3.9.2
    - flake8-import-order==0.18.1
    - flatbuffers==2.0
    - frozenlist==1.2.0
    - fsspec==2022.1.0
    - future==0.18.2
    - fvcore==0.1.5.post20220305
    - gdown==4.4.0
    - gitdb==4.0.9
    - gitpython==3.1.18
    - google-auth==2.6.2
    - google-auth-oauthlib==0.4.6
    - icevision==0.11.0
    - idna==3.3
    - idna-ssl==1.1.0
    - imageio==2.15.0
    - immutables==0.16
    - importlib-resources==5.4.0
    - iniconfig==1.1.1
    - iopath==0.1.9
    - joblib==1.1.0
    - kiwisolver==1.3.1
    - langcodes==3.3.0
    - loguru==0.6.0
    - matplotlib==3.3.4
    - mccabe==0.6.1
    - motmetrics==1.2.0
    - multidict==5.2.0
    - murmurhash==1.0.6
    - networkx==2.5.1
    - ninja==1.10.2.3
    - nose==1.3.7
    - oauthlib==3.2.0
    - omegaconf==2.1.1
    - opencv-python==4.5.5.64
    - opencv-python-headless==4.5.5.64
    - pandas==1.1.5
    - pathtools==0.1.2
    - pathy==0.6.1
    - pillow==8.4.0
    - pluggy==1.0.0
    - portalocker==2.4.0
    - preshed==3.0.6
    - prettytable==2.5.0
    - promise==2.3
    - psutil==5.9.0
    - py==1.11.0
    - py-cpuinfo==8.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycocotools==2.0.4
    - pycodestyle==2.7.0
    - pydantic==1.8.2
    - pydeprecate==0.3.1
    - pyflakes==2.3.1
    - pyparsing==3.0.7
    - pysocks==1.7.1
    - pytest==7.0.1
    - pytest-benchmark==3.4.1
    - pytorch-lightning==1.5.10
    - pytz==2021.3
    - pywavelets==1.1.1
    - pyyaml==6.0
    - qudida==0.0.4
    - requests==2.27.1
    - requests-oauthlib==1.3.1
    - resnest==0.0.6b20220319
    - rsa==4.8
    - scikit-image==0.17.2
    - scikit-learn==0.24.2
    - scipy==1.5.4
    - seaborn==0.11.2
    - sentry-sdk==1.5.8
    - setproctitle==1.2.2
    - setuptools==59.5.0
    - shapely==1.8.1.post1
    - shortuuid==1.0.8
    - smart-open==5.2.1
    - smmap==5.0.0
    - soupsieve==2.3.1
    - spacy==3.2.3
    - spacy-legacy==3.0.9
    - spacy-loggers==1.0.1
    - srsly==2.4.2
    - tabulate==0.8.9
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - thinc==8.0.15
    - thop==0.0.31-2005241907
    - threadpoolctl==3.1.0
    - tifffile==2020.9.3
    - timm==0.5.4
    - tomli==1.2.3
    - torch==1.10.1
    - torchmetrics==0.7.2
    - torchvision==0.11.2
    - tqdm==4.63.0
    - typer==0.4.0
    - typing-extensions==3.10.0.2
    - urllib3==1.26.9
    - wandb==0.12.11
    - wasabi==0.9.0
    - xmltodict==0.12.0
    - yacs==0.1.8
    - yarl==1.7.2
    - yaspin==2.0.0
prefix: /home/robotics/anaconda3/envs/ByteTrack
